# Generated by Django 4.1 on 2022-08-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('label', models.CharField(max_length=128)),
                ('source', models.URLField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'On hold'), (1, 'Valid')], default=0)),
            ],
        ),
    ]
