# Generated by Django 4.0.6 on 2022-08-15 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historichour',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(1500)]),
        ),
    ]
